In [2]:
import pandas as pd
import numpy as np
#simple Data Creation
data = {
    'Student_ID': [101, 102, 103, 104, 105],
    'Name': ['Saba', 'Ali', 'Sara', 'Ahmed', 'Zainab'],
    'Score': [93, 95, 56, 88, 89],
    'City': ['Islamabad', 'Karachi', 'Lohare', 'Karachi', 'Iran']

}
df = pd.DataFrame(data)
df

   Student_ID    Name  Score       City
0         101    Saba     93  Islamabad
1         102     Ali     95    Karachi
2         103    Sara     56     Lohare
3         104   Ahmed     88    Karachi
4         105  Zainab     89       Iran

In [3]:
df.head()

   Student_ID    Name  Score       City
0         101    Saba     93  Islamabad
1         102     Ali     95    Karachi
2         103    Sara     56     Lohare
3         104   Ahmed     88    Karachi
4         105  Zainab     89       Iran

In [4]:
df.describe()

       Student_ID     Score
count    5.000000   5.00000
mean   103.000000  84.20000
std      1.581139  16.02186
min    101.000000  56.00000
25%    102.000000  88.00000
50%    103.000000  89.00000
75%    104.000000  93.00000
max    105.000000  95.00000

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Student_ID  5 non-null      int64
 1   Name        5 non-null      str
 2   Score       5 non-null      int64
 3   City        5 non-null      str
dtypes: int64(2), str(2)
memory usage: 292.0 bytes